version:0.0
os: linux
files:
  - source: ./app/web2project/
    destination: /var/www/html
    overwrite: true
hooks:
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 180
      runas: root

